name: DB-Backup-image-builder
run-name: Triggered by ${{ github.event }} on ${{ github.ref }}
on:
  release:
    types: [published, prereleased, released]
  workflow_dispatch:
    
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      # - name: Python Linter
      #   uses: sunnysid3up/python-linter@master
      #   with:
      #     mypy-options: "--ignore-missing-imports --show-error-codes"
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Image builder
        env:
          AWS_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          SHA: ${{ github.sha }}
          REF: ${{ github.ref }}
        run: |
          TAG=$(echo $REF | cut -d '/' -f 3)
          REPO_NAME=$(echo $GITHUB_REPOSITORY | cut -d '/' -f 2 | tr '[:upper:]' '[:lower:]')
          docker build -t $AWS_REGISTRY/$REPO_NAME:$TAG -t $AWS_REGISTRY/$REPO_NAME:latest .
          docker push $AWS_REGISTRY/$REPO_NAME:$TAG
          docker push $AWS_REGISTRY/$REPO_NAME:latest
